"""
Ici repose toutes les variables global qui sont utilisées dans le fichier SystèmeSolaire.Py
"""

white = (255, 255, 255) # Couleur pour les trajectoires

pause = False

G = 6.67430 * 10**-11  # Constante gravitationnelle

# - MASSES DES PLANETES (en kg) -
MASSE_SOLEIL = 1.989 * 10**30         # Masse du Soleil
MASSE_MERCURE = 3.3 * 10**23          # Masse de Mercure
MASSE_VENUS = 4.87 * 10**24           # Masse de Venus
MASSE_TERRE = 5.972 * 10**24          # Masse de la Terre
MASSE_MARS = 6.42 * 10**23            # Masse de Mars
MASSE_JUPITER = 1.9 * 10**27          # Masse de Jupiter
MASSE_SATURNE = 5.684 * 10**26        # Masse de Saturne
MASSE_URANUS = 8.681 * 10**25         # Masse d'Uranus
MASSE_NEPTUNE = 1.024 * 10**26        # Masse de Neptune

# - COULEURS DES PLANETES (en RGB) -
COLOR_SOLEIL = (255, 255, 0)          # Couleur du Soleil
COLOR_MERCURE = (169, 169, 169)       # Couleur de Mercure
COLOR_VENUS = (255, 165, 0)           # Couleur de Venus
COLOR_TERRE = (0, 0, 255)             # Couleur de la Terre
COLOR_MARS = (255, 0, 0)              # Couleur de Mars
COLOR_JUPITER = (255, 140, 0)         # Couleur de Jupiter
COLOR_SATURNE = (210, 180, 140)       # Couleur de Saturne
COLOR_URANUS = (0, 255, 255)          # Couleur d'Uranus
COLOR_NEPTUNE = (0, 0, 139)           # Couleur de Neptune

# - DIAMETRES DES PLANETES (en km) -
DIAMETRE_SOLEIL = 1392000
DIAMETRE_MERCURE = 4879
DIAMETRE_VENUS = 12104
DIAMETRE_TERRE = 12742
DIAMETRE_MARS = 6794
DIAMETRE_MOYEN_JUPITER = 141403
DIAMETRE_MOYEN_SATURNE = 116464
DIAMETRE_MOYEN_URANUS = 51118
DIAMETRE_MOYEN_NEPTUNE = 49528

# - DISTANCES DES PLANETES AU SOLEIL (km converties en pixels) -
DISTANCE_MERCURE = 1160
DISTANCE_VENUS = 2160
DISTANCE_TERRE = 3000
DISTANCE_MARS = 4560
DISTANCE_JUPITER = 15560
DISTANCE_SATURNE = 28540
DISTANCE_URANUS = 57420
DISTANCE_NEPTUNE = 89900


# - VITESSES DES PLANETES (en km/s) -
VITESSE_MERCURE = 47.36
VITESSE_VENUS = 35.02
VITESSE_TERRE = 29.78
VITESSE_MARS = 24.077
VITESSE_JUPITER = 13.07
VITESSE_SATURNE = 9.69
VITESSE_URANUS = 6.81
VITESSE_NEPTUNE = 5.43

# - NOUVELLE VITESSE DES PLANETES AVEC ECHELLES -
nv_VITESSE_MERCURE = VITESSE_MERCURE / DISTANCE_MERCURE
nv_VITESSE_VENUS = VITESSE_VENUS / DISTANCE_VENUS
nv_VITESSE_TERRE = VITESSE_TERRE / DISTANCE_TERRE
nv_VITESSE_MARS = VITESSE_MARS / DISTANCE_MARS
nv_VITESSE_JUPITER = VITESSE_JUPITER / DISTANCE_JUPITER
nv_VITESSE_SATURNE = VITESSE_SATURNE / DISTANCE_SATURNE
nv_VITESSE_URANUS =  VITESSE_URANUS / DISTANCE_URANUS
nv_VITESSE_NEPTUNE = VITESSE_NEPTUNE / DISTANCE_NEPTUNE

FACTEUR_TEMPS = 0.02

# - REDEF DES TAILLES (EN PIXELS) -
TAILLE_SOLEIL = 250
TAILLE_MERCURE = 35
TAILLE_VENUS = 37
TAILLE_TERRE = 38
TAILLE_MARS = 36
TAILLE_JUPITER = 45
TAILLE_SATURNE = 43
TAILLE_URANUS = 41
TAILLE_NEPTUNE = 40
